name: Send Text Message Manual

on: workflow_dispatch
jobs:
  data_refresh:
    name: Create and populate .Renviron file
      run: |
        echo PHONE_NUMBER_MOM = "$PHONE_NUMBER_MOM" >> ~/.Renviron
        echo PHONE_NUMBER_JP  = "$PHONE_NUMBER_JP"  >> ~/.Renviron
        shell: bash
    name: send a message
    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      PHONE_NUMBER_MOM: ${{ secrets.PHONE_NUMBER_MOM }}
      PHONE_NUMBER_JP:  ${{ secrets.PHONE_NUMBER_JP }}
    runs-on: ubuntu-18.04
    container:
     image: docker.io/richpauloo/twm:prod.0.0.01
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: Send text message
        run: bash ./R/run.sh  
