name: Send Twilio Text Message Manual

on: workflow_dispatch
jobs:
  data_refresh:
    name: send a message
    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      TARGET_PHONE_NUMBER: ${{ secrets.TARGET_PHONE_NUMBER }}
      DEPLOY_DATE: ${{ secrets.DEPLOY_DATE }}
    runs-on: ubuntu-18.04
    container:
     image: docker.io/richpauloo/dockertest:prod.0.0.01
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: Send text message
        run: Rscript .R/message.R
